### ISSUE TITLE
Problems running the sample script

### ISSUE THREAD

**Issue by joshuasami** [cumc-dbmi/cehrbert#73]
Hey, 

Thank you for the nice repo! We are trying to adapt your approach to EHRs from Germany and it really is interesting.

While running the example script, with the example data, from the ReadME, I ran into some problems. 

When streaming is enabled, I get the following error:
> Traceback (most recent call last):
>   File "/user/.conda/envs/cehr-bert-gfl/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/user/.conda/envs/cehr-bert-gfl/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/mnt/home/projects/TransformersOnGermanEHR/original_repo/cehrbert/src/cehrbert/runners/hf_cehrbert_pretrain_runner.py", line 297, in <module>
>     main()
>   File "/mnt/home/projects/TransformersOnGermanEHR/original_repo/cehrbert/src/cehrbert/runners/hf_cehrbert_pretrain_runner.py", line 222, in main
>     processed_dataset = create_cehrbert_pretraining_dataset(
>   File "/mnt/home/projects/TransformersOnDADB/original_repo/cehrbert/src/cehrbert/data_generators/hf_data_generator/hf_dataset.py", line 50, in create_cehrbert_pretraining_dataset
>     dataset = dataset.filter(
>   File "/user/.conda/envs/cehr-bert-gfl/lib/python3.10/site-packages/datasets/dataset_dict.py", line 971, in filter
>     self._check_values_type()
>   File "/user/.conda/envs/cehr-bert-gfl/lib/python3.10/site-packages/datasets/dataset_dict.py", line 51, in _check_values_type
>     raise TypeError(f"Values in `DatasetDict` should be of type `Dataset` but got type '{type(dataset)}'")
> TypeError: Values in `DatasetDict` should be of type `Dataset` but got type '<class 'datasets.iterable_dataset.IterableDataset'>'

I was able to lose the error, by changing the _create_cehrbert_pretraining_dataset_ method in _hf_dataset.py_ to the following. Is that an alright solution or is there something more, that has to be fixed?

``` python
def create_cehrbert_pretraining_dataset(
    dataset: Union[Dataset, DatasetDict],
    concept_tokenizer: CehrBertTokenizer,
    data_args: DataTrainingArguments,
) -> Dataset:
    required_columns = TRANSFORMER_COLUMNS + CEHRBERT_COLUMNS

    # Remove patients without any records
    # check if DatatsetDict or IterableDatasetDict, if so, filter each dataset
    if isinstance(dataset, DatasetDict) or isinstance(dataset, IterableDatasetDict):
        for key in dataset.keys():
            dataset[key] = dataset[key].filter(
                lambda batch: [num_of_concepts > 0 for num_of_concepts in batch["num_of_concepts"]],
                batched=True,
                batch_size=data_args.preprocessing_batch_size,
            )
    else:
        dataset = dataset.filter(
            lambda batch: [num_of_concepts > 0 for num_of_concepts in batch["num_of_concepts"]],
            num_proc=data_args.preprocessing_num_workers if not data_args.streaming else None,
            batched=True,
            batch_size=data_args.preprocessing_batch_size,
        )

...
```

I also noticed, that there is a different error, when streaming is disabled. I didn't look further into that one, though.

>   File "/user/.conda/envs/cehr-bert-gfl/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/user/.conda/envs/cehr-bert-gfl/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/mnt/home/projects/TransformersOnGermanEHR/original_repo/cehrbert/src/cehrbert/runners/hf_cehrbert_pretrain_runner.py", line 297, in <module>
>     main()
>   File "/mnt/home/projects/TransformersOnGermanEHR/original_repo/cehrbert/src/cehrbert/runners/hf_cehrbert_pretrain_runner.py", line 287, in main
>     train_result = trainer.train(resume_from_checkpoint=checkpoint)
>   File "/user/.conda/envs/cehr-bert-gfl/lib/python3.10/site-packages/transformers/trainer.py", line 1780, in train
>     return inner_training_loop(
>   File "/user/.conda/envs/cehr-bert-gfl/lib/python3.10/site-packages/transformers/trainer.py", line 2213, in _inner_training_loop
>     self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
>   File "/user/.conda/envs/cehr-bert-gfl/lib/python3.10/site-packages/transformers/trainer.py", line 2577, in _maybe_log_save_evaluate
>     metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
>   File "/user/.conda/envs/cehr-bert-gfl/lib/python3.10/site-packages/transformers/trainer.py", line 3358, in evaluate
>     eval_dataloader = self.get_eval_dataloader(eval_dataset)
>   File "/user/.conda/envs/cehr-bert-gfl/lib/python3.10/site-packages/transformers/trainer.py", line 894, in get_eval_dataloader
>     raise ValueError("Trainer: evaluation requires an eval_dataset.")
> ValueError: Trainer: evaluation requires an eval_dataset.

Best Wishes
Sami

**Comment by ChaoPang** [comment]
@joshuasami thanks for reporting the issues, your fix is good, The filter function cannot be applied to a DatasetDict of IterableDataset, I will create a PR for this. I need to look at the other issue

**Comment by ChaoPang** [comment]
Thanks for catching the second error as well, the following line generates DatasetDict with split names train and test, but the trainer expected a validation split instead of a test split, I fixed that in the same PR. I added you as a collaborator to the Repo so you can review the PR, you should have received an invite to the repo

```
dataset = dataset.train_test_split(
    test_size=data_args.validation_split_percentage,
    seed=training_args.seed,
)
```

**Comment by ChaoPang** [comment]
The PR has been reviewed and merged by colleague, and these two issues should be fixed in the main branch.
